### ISSUE TITLE
References cited in your presentation

### ISSUE THREAD

**Issue by tranlm** [ilblackdragon/adversarial_workshop#2]
Hi Illia,

I'm trying to look into the references you cite in your presentation (e.g. Goodfellow 2015, Miyato 2016) and am having trouble locating the exact ones. Would you mind posting the papers you're referring to?

thanks!

**Comment by ilblackdragon** [comment]
Sure:
- Gal and Ghahramani, 2015: https://arxiv.org/pdf/1512.05287v5
- Srivastava et al., 2015: https://www.cs.toronto.edu/~hinton/absps/JMLRdropout.pdf
- Goodfellow et al., 2015: https://arxiv.org/pdf/1412.6572v3
- Miyato et al., 2016: https://arxiv.org/pdf/1507.00677v9

**Comment by ilblackdragon** [comment]
Added to readme. Hope this helps!
